### ISSUE TITLE
Cannot destructure property 'menus' of '(intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by mendozalz** [JEverhart383/astro-wordpress-starter#11]
[https://ibb.co/rQSpHwk](url)

**Comment by JEverhart383** [comment]
Thanks for opening an issue for this. The error you see is generally because your menu isn't configured in the same way the starter expects. First, I'd make sure you have a theme that allows traditional menu registration, not a block or FSE theme. Then, confirm that menus location is set to 'Primary'

**Comment by mendozalz** [comment]
Jeff, I'm really grateful for answering me and for the next person who reads this, I'll tell you that what Jeff refers to with FSE (Full Site Editing) are those themes that allow you to edit global changes, such as the WP core theme " Twenty Twenty-Three " to solve this problem just change to "Twenty Twenty-One " and solved. By the way Jeff, is there a website that can explain what you have created step by step? It's like understanding everything more clearly. Thank you very much for reading me.

**Comment by JEverhart383** [comment]
Thanks for confirming @3P4R4 , I'll add something to the README to let people know. Going to close this issue. Thanks for using the starter!
